Repository apache/pulsar-manager, pull requests merged in 2019-11, with the labels that each got.

#207 Add license for vue file
  front-end/build/build.js
  front-end/build/check-versions.js
  front-end/build/utils.js
  front-end/build/vue-loader.conf.js
  front-end/build/webpack.base.conf.js
  front-end/build/webpack.dev.conf.js
  front-end/build/webpack.prod.conf.js
  front-end/config/dev.env.js
  front-end/config/index.js
  front-end/config/prod.env.js
  front-end/config/sit.env.js
  front-end/src/App.vue
  front-end/src/components/Breadcrumb/index.vue
  front-end/src/components/CodeEditor/index.vue
  front-end/src/components/ErrorLog/index.vue
  front-end/src/components/Hamburger/index.vue
  front-end/src/components/JsonEditor/index.vue
  front-end/src/components/LangSelect/index.vue
  front-end/src/components/MDinput/index.vue
  front-end/src/components/Pagination/index.vue
  front-end/src/components/PanThumb/index.vue
  front-end/src/components/ScrollPane/index.vue
  front-end/src/components/SizeSelect/index.vue
  front-end/src/components/Sticky/index.vue
  front-end/src/components/SvgIcon/index.vue
  front-end/src/views/dashboard/grafana/index.vue
  front-end/src/views/dashboard/prometheus/index.vue
  front-end/src/views/errorPage/401.vue
  front-end/src/views/errorPage/404.vue
  front-end/src/views/layout/Layout.vue
  front-end/src/views/layout/components/AppMain.vue
  front-end/src/views/layout/components/Navbar.vue
  front-end/src/views/layout/components/Sidebar/Item.vue
  front-end/src/views/layout/components/Sidebar/Link.vue
  front-end/src/views/layout/components/Sidebar/SidebarItem.vue
  front-end/src/views/layout/components/Sidebar/index.vue
  front-end/src/views/layout/components/TagsView.vue
  front-end/src/views/login/authredirect.vue
  front-end/src/views/login/index.vue
  front-end/src/views/login/socialsignin.vue
  front-end/src/views/management/bookies/bookie.vue
  front-end/src/views/management/bookies/index.vue
  front-end/src/views/management/brokers/broker.vue
  front-end/src/views/management/clusters/cluster.vue
  front-end/src/views/management/clusters/failureDomain.vue
  front-end/src/views/management/clusters/index.vue
  front-end/src/views/management/environments/index.vue
  front-end/src/views/management/functions/index.vue
  front-end/src/views/management/namespaceIsolations/namespaceIsolationPolicy.vue
  front-end/src/views/management/namespaces/namespace.vue
  front-end/src/views/management/sinks/index.vue
  front-end/src/views/management/sources/index.vue
  front-end/src/views/management/subscriptions/subscription.vue
  front-end/src/views/management/tenants/index.vue
  front-end/src/views/management/tenants/tenant.vue
  front-end/src/views/management/tokens/index.vue
  front-end/src/views/management/topics/partitionedTopic.vue
  front-end/src/views/management/topics/topic.vue
  front-end/src/views/redirect/index.vue
  gradle/license.gradle
Labels: area/backend

#213 Remove streamnative from the project
  CONTRIBUTING.md
  README.md
  docker/Dockerfile
  docs/developer-guide.md
  front-end/README.md
  front-end/package.json
  src/README.md
Labels: area/documentation

#211 Update readme for start backend service
  README.md
  docker/Dockerfile
  docker/supervisord.conf
  src/README.md
Labels: area/documentation

#212 Ugrade HerdDB to 0.13.0
  gradle.properties
Labels: area/backend, type/enhancement

#217 Move version to 0.2.0
  VERSION
  front-end/package.json
Labels: area/backend, area/frontend

#223 Fix README.md display problems
  README.md
Labels: area/backend, area/documentation
