Repository apache/pulsar-manager, pull requests merged in 2019-09, with the labels that each got.

#179 Fix reset cursor by time
  front-end/src/lang/en.js
  front-end/src/lang/zh.js
  front-end/src/views/management/subscriptions/subscription.vue
  front-end/src/views/management/topics/partitionedTopic.vue
Labels: area/frontend, type/bug

#187 Fix wrong broker display error
  front-end/src/views/management/clusters/cluster.vue
Labels: area/frontend, type/bug

#189 Remove dependency package jszip
  front-end/package.json
  front-end/src/vendor/Export2Zip.js
Labels: area/frontend

#186 Add developer guide
  docs/developer-guide.md
  docs/img/frontend-code.png
  docs/img/pulsar-manager-architecture.png
  docs/img/pulsar-manager-backend-code.png
  docs/img/tenants-api.png
  docs/img/tenants-controller.png
  docs/img/tenants-service-impl-test.png
  docs/img/tenants-service-impl.png
  docs/img/tenants-service.png
Labels: area/documentation

#191 Fix logging level
  src/main/resources/application.properties
Labels: area/backend, type/bug

#193 Fix wrong place for license scan badge in README.md (#192)
  README.md
Labels: area/documentation
