Repository apache/pulsar-manager, pull requests merged in 2019-10, with the labels that each got.

#197 Make default environment persistent
  .gitignore
  gradle.properties
  src/main/resources/application.properties
Labels: area/backend, type/enhancement

#201 Support gradle bump version
  build.gradle
  front-end/package.json
Labels: area/build

#203 Added JWT Token Support
  .gitignore
  front-end/src/utils/request.js
  src/main/java/io/streamnative/pulsar/manager/controller/EnvironmentsController.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/BookiesServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/BrokersServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/ClustersServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/EnvironmentCacheServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/TenantsServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/service/impl/TopicsServiceImpl.java
  src/main/java/io/streamnative/pulsar/manager/zuul/EnvironmentForward.java
  src/main/resources/application.properties
  src/test/java/io/streamnative/pulsar/manager/service/BookiesServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/BrokerStatsServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/BrokersServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/ClustersServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/NamespacesServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/TenantsServiceImplTest.java
  src/test/java/io/streamnative/pulsar/manager/service/TopicsServiceImplTest.java
Labels: area/backend, type/enhancement

#202 Delete code owner
  .github/CODEOWNERS
Labels: type/enhancement

#204 Support redirect.scheme
  src/main/java/io/streamnative/pulsar/manager/zuul/LocationHeaderRewritingFilter.java
  src/main/resources/application.properties
Labels: area/backend
