Repository apache/pulsar-manager, pull requests merged in 2019-12, with the labels that each got.

#222 Support third party login for example GitHub
  build.gradle
  front-end/src/api/socialsignin.js
  front-end/src/icons/svg/github.svg
  front-end/src/views/login/index.vue
  front-end/src/views/login/socialsignin.vue
  src/README.md
  src/main/java/org/apache/pulsar/manager/controller/ThirdPartyLoginCallbackController.java
  src/main/java/org/apache/pulsar/manager/dao/UsersRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/entity/GithubAuthEntity.java
  src/main/java/org/apache/pulsar/manager/entity/GithubUserInfoEntity.java
  src/main/java/org/apache/pulsar/manager/entity/UserInfoEntity.java
  src/main/java/org/apache/pulsar/manager/entity/UsersRepository.java
  src/main/java/org/apache/pulsar/manager/interceptor/WebAppConfigurer.java
  src/main/java/org/apache/pulsar/manager/mapper/UsersMapper.java
  src/main/java/org/apache/pulsar/manager/service/ThirdPartyLoginService.java
  src/main/java/org/apache/pulsar/manager/service/impl/GithubLoginServiceImpl.java
  src/main/java/org/apache/pulsar/manager/utils/HttpUtil.java
  src/main/resources/META-INF/sql/herddb-schema.sql
  src/main/resources/META-INF/sql/mysql-schema.sql
  src/main/resources/META-INF/sql/postgresql-schema.sql
  src/main/resources/META-INF/sql/sqlite-schema.sql
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/test/java/org/apache/pulsar/manager/dao/UsersRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/service/GithubLoginServiceImplTest.java
Labels: area/backend, area/frontend, type/task

#227 Fix typos in comments, names of methods and variables
  README.md
  src/main/java/org/apache/pulsar/manager/controller/BrokerStatsController.java
  src/main/java/org/apache/pulsar/manager/controller/BrokerTokensController.java
  src/main/java/org/apache/pulsar/manager/controller/ClustersController.java
  src/main/java/org/apache/pulsar/manager/controller/EnvironmentsController.java
  src/main/java/org/apache/pulsar/manager/controller/NamespacesController.java
  src/main/java/org/apache/pulsar/manager/service/BrokerStatsService.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TopicsServiceImpl.java
  src/test/java/org/apache/pulsar/manager/service/TopicsServiceImplTest.java
Labels: area/backend, type/enhancement

#228 Exclude test dependencies from the final product
  build.gradle
Labels: area/backend, type/enhancement

#229 Remove redundant local variables from services' implementation
  src/main/java/org/apache/pulsar/manager/controller/TopicsController.java
  src/main/java/org/apache/pulsar/manager/dao/ConsumersStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/dao/PublishersStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/dao/ReplicationsStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/dao/SubscriptionsStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/dao/TopicsStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/dao/UsersRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/EnvironmentCacheServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/JwtServiceImpl.java
Labels: area/backend, type/enhancement

#230 Switch from field injection to constructor injection of beans
  src/main/java/org/apache/pulsar/manager/controller/BookiesController.java
  src/main/java/org/apache/pulsar/manager/controller/BrokerStatsController.java
  src/main/java/org/apache/pulsar/manager/controller/BrokerTokensController.java
  src/main/java/org/apache/pulsar/manager/controller/BrokersController.java
  src/main/java/org/apache/pulsar/manager/controller/ClustersController.java
  src/main/java/org/apache/pulsar/manager/controller/EnvironmentsController.java
  src/main/java/org/apache/pulsar/manager/controller/LoginController.java
  src/main/java/org/apache/pulsar/manager/controller/NamespacesController.java
  src/main/java/org/apache/pulsar/manager/controller/TenantsController.java
  src/main/java/org/apache/pulsar/manager/controller/ThirdPartyLoginCallbackController.java
  src/main/java/org/apache/pulsar/manager/controller/TopicsController.java
  src/main/java/org/apache/pulsar/manager/interceptor/AdminHandlerInterceptor.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/ClustersServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/EnvironmentCacheServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TopicsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/main/java/org/apache/pulsar/manager/zuul/LocationHeaderRewritingFilter.java
Labels: area/backend, type/enhancement

#235 Ugrade HerdDB to 0.13.1
  gradle.properties
Labels: area/backend, type/enhancement

#237 Add github pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type/enhancement, type/task

#236 Add a configuration file for backend service of pulsar manager
  docker/Dockerfile
  docker/entrypoint.sh
  docker/supervisord-configuration-file.conf
Labels: area/backend, type/enhancement

#239 Support display stats for tenant and namespaces
  front-end/src/views/management/tenants/index.vue
  front-end/src/views/management/tenants/tenant.vue
  src/main/java/org/apache/pulsar/manager/dao/TopicsStatsRepositoryImpl.java
  src/main/java/org/apache/pulsar/manager/entity/TopicsStatsRepository.java
  src/main/java/org/apache/pulsar/manager/mapper/TopicsStatsMapper.java
  src/main/java/org/apache/pulsar/manager/service/BrokerStatsService.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TenantsServiceImpl.java
  src/test/java/org/apache/pulsar/manager/service/BrokerStatsServiceImplTest.java
Labels: area/backend, area/frontend, type/enhancement

#240 Support sub and unsub
  front-end/src/api/subscriptions.js
  front-end/src/lang/en.js
  front-end/src/lang/zh.js
  front-end/src/utils/request.js
  front-end/src/views/management/topics/partitionedTopic.vue
  front-end/src/views/management/topics/topic.vue
Labels: area/frontend, type/enhancement

#243 Fixed display stats for tenant and namespace
  src/main/java/org/apache/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TenantsServiceImpl.java
Labels: area/backend, type/bug
