Repository apache/pulsar-manager, pull requests merged in 2020-04, with the labels that each got.

#285 Upgrade HerdDB to 0.15.1
  build.gradle
  gradle.properties
Labels: type/enhancement

#287 Add a docker compose file and update README
  .github/workflows/gradle.yml
  .gitignore
  README.md
  docker/data/.keep
  docker/docker-compose.yml
  docs/img/pulsar-manager-arch.png
Labels: area/build, area/documentation

#290 Use .asf.yaml file for managing pulsar-manager project settings
  .asf.yaml
Labels: area/documentation

#288 Serve frontend directly from Pulsar Manager backend process
  src/main/java/org/apache/pulsar/manager/interceptor/AdminHandlerInterceptor.java
  src/main/java/org/apache/pulsar/manager/interceptor/WebAppConfigurer.java
Labels: type/enhancement

#295 Using volumes instead of binding mounts
  README.md
Labels: area/documentation, type/enhancement
