Repository apache/pulsar-manager, pull requests merged in 2020-07, with the labels that each got.

#314 Update README.md regarding issues/283
  README.md
Labels: area/documentation

#316 Change default port and replace request uri
  README.md
  build.gradle
  front-end/src/api/tokens.js
  front-end/src/store/modules/user.js
  front-end/src/utils/csrfToken.js
  front-end/src/utils/request.js
  front-end/src/views/login/index.vue
  src/main/java/org/apache/pulsar/manager/controller/CsrfTokenController.java
  src/main/java/org/apache/pulsar/manager/interceptor/AdminHandlerInterceptor.java
  src/main/java/org/apache/pulsar/manager/interceptor/WebAppConfigurer.java
  src/main/java/org/apache/pulsar/manager/security/SecurityConfig.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/main/resources/application.properties
Labels: area/backend, area/documentation, area/frontend, type/enhancement

#315 Use PulsarAdmin instead of HttpUtil in BrokerStatsServiceImpl
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
Labels: area/backend, type/enhancement

#317 Remove unused fields in BrokerStatsServiceImpl
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
Labels: area/backend
