Repository apache/pulsar-manager, pull requests merged in 2020-02, with the labels that each got.

#241 Support peek messages from pulsar broker
  build.gradle
  front-end/src/api/subscriptions.js
  front-end/src/lang/en.js
  front-end/src/lang/zh.js
  front-end/src/views/management/subscriptions/subscription.vue
  front-end/src/views/management/topics/partitionedTopic.vue
  front-end/src/views/management/topics/topic.vue
  front-end/src/views/management/users/index.vue
  gradle.properties
  src/main/java/org/apache/pulsar/manager/controller/TopicsController.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/main/resources/application.properties
Labels: area/backend, area/frontend, type/task

#258 Support https forward
  README.md
  front-end/src/router/index.js
  front-end/src/views/management/subscriptions/subscription.vue
  src/README.md
  src/main/java/org/apache/pulsar/manager/controller/TopicsController.java
  src/main/java/org/apache/pulsar/manager/utils/HttpUtil.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/main/java/org/apache/pulsar/manager/zuul/HttpsClientConfiguration.java
  src/main/resources/application.properties
Labels: type/enhancement, type/task

#264 Update supervisord-private-key.conf
  docker/supervisord-private-key.conf
Labels: type/bug

#262 Updated supervisord-secret-key.conf
  docker/supervisord-secret-key.conf
Labels: type/bug

#263 Fixed DB initialization for Docker
  docker/init_db.sql
Labels: area/build, type/bug
