Repository apache/pulsar-manager, pull requests merged in 2020-09, with the labels that each got.

#330 Upgrade HerdDB to 0.19.0
  gradle.properties
Labels: type/enhancement

#331 Upgrade BKVM to 2.0.0
  gradle.properties
Labels: area/build, type/enhancement

#332 Fixed docker package
  VERSION
  docker/default.conf
  docker/entrypoint.sh
  docker/supervisord-configuration-file.conf
Labels: area/build, type/enhancement

#334 Activate BKVM metadata reload at boot
  src/main/resources/bkvm.conf
Labels: type/enhancement

#339 Fixed mysql schema field token error
  src/main/resources/META-INF/sql/mysql-schema.sql
Labels: type/bug

#337 Update readme file
  README.md
  docker/data/.keep
  docker/docker-compose.yml
  front-end/README.md
  front-end/config/index.js
  src/README.md
Labels: area/backend, area/documentation, area/frontend
