Repository apache/pulsar-manager, pull requests merged in 2020-12, with the labels that each got.

#356 Passing LoggerFactory to @Slf4j lombok notation
  src/main/java/org/apache/pulsar/manager/PulsarApplicationListener.java
  src/main/java/org/apache/pulsar/manager/controller/EnvironmentsController.java
  src/main/java/org/apache/pulsar/manager/interceptor/WebAppConfigurer.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokersServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/ClustersServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/PulsarAdminServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TenantsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TopicsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/utils/HttpUtil.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/test/java/org/apache/pulsar/manager/profiles/HerdDBTestProfile.java
  src/test/java/org/apache/pulsar/manager/profiles/SqliteDBTestProfile.java
Labels: area/backend, type/enhancement

#360 Issue 359: Upgrade BKVM to 3.0.0
  build.gradle
  gradle.properties
  src/test/java/org/apache/pulsar/manager/service/TopicsServiceImplTest.java
Labels: type/enhancement

#364 create /data dir
  docker/entrypoint.sh
Labels: area/build, type/enhancement

#366 fix ISSUE-365: Some mistakes in README.md of the master branch
  README.md
Labels: area/documentation, type/enhancement
