Repository apache/pulsar-manager, pull requests merged in 2020-06, with the labels that each got.

#306 Support multi address for broker stats
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
Labels: area/backend, type/bug

#300 Bundle BKVM.org - BookKeeper Visual Manager 1.2.0
  README.md
  build.gradle
  gradle.properties
  src/main/java/org/apache/pulsar/manager/EmbeddedTomcatCustomizer.java
  src/main/java/org/apache/pulsar/manager/interceptor/WebAppConfigurer.java
  src/main/resources/application.properties
  src/main/resources/bkvm.conf
Labels: area/backend, area/frontend

#286 Use Pulsar Admin instead of HttpUtil
  build.gradle
  gradle.properties
  src/main/java/org/apache/pulsar/manager/PulsarApplicationListener.java
  src/main/java/org/apache/pulsar/manager/controller/BrokerStatsController.java
  src/main/java/org/apache/pulsar/manager/controller/EnvironmentsController.java
  src/main/java/org/apache/pulsar/manager/controller/TopicsController.java
  src/main/java/org/apache/pulsar/manager/controller/exception/PulsarAdminOperationException.java
  src/main/java/org/apache/pulsar/manager/service/BrokerStatsService.java
  src/main/java/org/apache/pulsar/manager/service/PulsarAdminService.java
  src/main/java/org/apache/pulsar/manager/service/TopicsService.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokerStatsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/BrokersServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/ClustersServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/EnvironmentCacheServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/NamespacesServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/PulsarAdminServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TenantsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/service/impl/TopicsServiceImpl.java
  src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java
  src/main/resources/application.properties
  src/test/java/org/apache/pulsar/manager/dao/BrokerTokensRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/EnvironmentsRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/NamespacesRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/RoleBindingRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/RolesRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/TenantsRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/dao/UsersRepositoryImplTest.java
  src/test/java/org/apache/pulsar/manager/service/BookiesServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/BrokerStatsServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/BrokerTokensServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/BrokersServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/ClustersServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/EnvironmentCacheServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/GithubLoginServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/NamespacesServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/PulsarAdminServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/PulsarEventImplTest.java
  src/test/java/org/apache/pulsar/manager/service/RoleBindingServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/RolesServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/TenantsServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/TopicsServiceImplTest.java
  src/test/java/org/apache/pulsar/manager/service/UsersServiceImplTest.java
Labels: area/backend
